#####################################################################################
# A default configuration that will be loaded for all jupyter books
# See the documentation for help and more options:
# https://jupyterbook.org/customize/config.html

#######################################################################################
# Book settings
title: Classifying 19th Century British Library books using Crowdsourcing and Machine Learning # The title of the book. Will be placed in the left navbar.
author: Daniel van Strien, Giorgia Tolfo, Victoria Morris, Kaspar Beelen
copyright: "2021 The Alan Turing Institute, British Library Board, Queen Mary University of London, University of Exeter, University of East Anglia and University of Cambridge." # Copyright year to be placed in the footer
logo: logo.jpg # A path to the book logo
execute:
  execute_notebooks: "off"
bibtex_bibfiles:
  - references.bib
launch_buttons:
  colab_url: "https://colab.research.google.com"
latex:
  latex_engine: lualatex
html:
  use_repository_button: true
  comments:
    hypothesis: true

repository:
  url: "https://github.com/Living-with-machines/genre-classification" # The URL to your book's repository
  path_to_book: "genre_classification_of_bl_books/"  # A path to your book's folder, relative to the repository root.
  branch: main
